# permissions for end users to view dinosaurs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-kustomization-inside
    app.kubernetes.io/managed-by: kustomize
  name: dinosaur-viewer-role
rules:
- apiGroups:
  - deployer.deploydocus.io
  resources:
  - dinosaurs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployer.deploydocus.io
  resources:
  - dinosaurs/status
  verbs:
  - get
